### ISSUE TITLE
Apollo Server v3

### ISSUE THREAD

**Issue by callmephilip** [azath-dev/apollo-server-plugin-server-timing#27]
Is this plugin broken with Apollo Server v3? Probably due to tracing support, I assume (https://github.com/apollographql/apollo-tracing#apollo-tracing)

**Comment by FezVrasta** [comment]
@jmandzik it'd be great if you upgraded this plugin to work with 3.x and 4.x, I can't find anything similar out there :-(

**Comment by jmandzik** [comment]
Unfortunately, I'm a few years removed from the Apollo ecosystem and have no plans of updating this.  Feel free to fork and run with the ideas!
